export const VALUE_TO_LABEL_MAP: any = {
  tomato: 'Томатный',
  white: 'Белый',
  spicy: 'Острый',
  mozzarella: 'Моцарелла',
  cheddar: 'Чеддер',
  blue: 'Дор Блю',
  bacon: 'Бекон',
  pepperoni: 'Пепперони',
  ham: 'Ветчина',
  tomatos: 'Помидоры',
  mushroom: 'Грибы',
  pepper: 'Перец',
  thin: 'Тонкое',
  thick: 'Пышное',
  30: '30 см',
  35: '35 см',
};
